// FR-HOOK-0009 — ordered bootstrap manifest + prefix text
// Decoded from baseline agents/TEMP/old-gen-r2/core-claude/hooks/hooks.json

import type { BootstrapEntryRef } from '../types.js';

/**
 * The bootstrap prefix text prepended to the lead document's additionalContext.
 * Decoded verbatim from baseline entry 0 (plugin-files-mode).
 * FR-HOOK-0003
 */
export const BOOTSTRAP_PREFIX =
  'ALWAYS MUST FULLY READ THIS ENTIRE CONTEXT BEFORE PROCEEDING FROM FILE PATH PROVIDED ESPECIALLY IF TRUNCATED/PREVIEWED. DO IT NOW! THEN PROCEED.\nRosetta get_context_instructions:\n\n';

/**
 * The canonical ordered manifest of bootstrap document basenames.
 * Only present documents (those in the target's VFS/frames) are included — engine is content-agnostic.
 * The plugin-root entry is NOT in this list — it is appended separately (GT-3.4).
 * FR-HOOK-0009, GT-2.1
 */
export const BOOTSTRAP_MANIFEST_ORDER: ReadonlyArray<BootstrapEntryRef> = [
  { basename: 'plugin-files-mode', isLead: true },   // lead doc — gets the prefix
  { basename: 'bootstrap-core-policy', isLead: false },
  { basename: 'bootstrap-execution-policy', isLead: false },
  { basename: 'bootstrap-hitl-questioning', isLead: false }, // r2-only; r3 has different set
  { basename: 'bootstrap-guardrails', isLead: false },
  { basename: 'bootstrap-rosetta-files', isLead: false },
  // Index entries (positions 6 & 7 — included when includeIndexEntries is true)
  // These are virtual entries generated by pluginGenerateIndexes:
  { basename: '__rules_index__', isLead: false },     // rules/INDEX.md
  { basename: '__workflows_index__', isLead: false },  // workflows/INDEX.md (or commands/)
];

/**
 * The fixed manifest for the plugin-root entry (GT-3.4).
 * One per IDE target, decoded from baseline.
 */
export const CLAUDE_PLUGIN_ROOT_ENTRY = {
  command: `printf '%s' "{\\"hookSpecificOutput\\":{\\"hookEventName\\":\\"SessionStart\\",\\"additionalContext\\":\\"Rosetta Plugin Path: \${CLAUDE_PLUGIN_ROOT}\\"}}"`,
};

export const CODEX_PLUGIN_ROOT_COMMAND =
  `workspace_root="$PWD"; ` +
  `while [ "$workspace_root" != "/" ] && [ ! -f "$workspace_root/.agents/rules/bootstrap-rosetta-files.md" ]; do ` +
  `workspace_root="$(dirname "$workspace_root")"; ` +
  `done; ` +
  `if [ -f "$workspace_root/.agents/rules/bootstrap-rosetta-files.md" ]; then ` +
  `printf '%s' "{\\"hookSpecificOutput\\":{\\"hookEventName\\":\\"SessionStart\\",\\"additionalContext\\":\\"Rosetta Plugin Path: $workspace_root/.agents\\"}}"; ` +
  `fi`;

export const COPILOT_PLUGIN_ROOT_BASH =
  `for base in "$HOME/.vscode/agent-plugins" "$HOME/.local/share/Code/agentPlugins"; ` +
  `do root="$base/github.com/griddynamics/rosetta/plugins/core-copilot"; ` +
  `if [ -f "$root/commands/coding-flow.md" ]; then ` +
  `printf '%s' "{\\"hookSpecificOutput\\":{\\"hookEventName\\":\\"SessionStart\\",\\"additionalContext\\":\\"Rosetta Plugin Path: $root\\"}}"; ` +
  `break; ` +
  `fi; ` +
  `done`;

export const COPILOT_PLUGIN_ROOT_POWERSHELL =
  `$root = "$env:LOCALAPPDATA\\Code\\agentPlugins\\github.com\\griddynamics\\rosetta\\plugins\\core-copilot"; ` +
  `if (Test-Path "$root\\commands\\coding-flow.md") { ` +
  `Write-Output ('{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"Rosetta Plugin Path: ' + $root + '"}}') ` +
  `}`;

/**
 * The cursor plugin-root entry command.
 * Uses double-quoted printf for env var expansion; additional_context shape (NOT hookSpecificOutput).
 * GT-3.4 cursor variant.
 */
export const CURSOR_PLUGIN_ROOT_ENTRY = {
  command: `printf '{"additional_context":"Rosetta Plugin Path: %s"}' "\${CURSOR_PROJECT_DIR}"`,
};
